FROM maven:3.6.3-jdk-11-openj9 as maven
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
#RUN mvn -B -e -C -T 1C dependency:go-offline

COPY src/ /build/src/
RUN mvn package
#RUN mvn -B -e -o -T 1C verify

# Step : Package image
FROM adoptopenjdk:11-jre-hotspot
#ENTRYPOINT exec java $JAVA_OPTS -jar /app/my-app.jar
ENTRYPOINT ["java","-jar","/app/my-app.jar"]
COPY --from=maven /build/target/*jar-with-dependencies.jar /app/my-app.jar

